#!/bin/bash

THEME="trinity-and-neo"

export BACKGROUND_COLOR="#10110c"
export BACKGROUND_ALT_COLOR="#1a1a14"
export FOREGROUND_COLOR="#dae2e5"
export PRIMARY_COLOR="#c8ab9a"
export SECONDARY_COLOR="#8ABEB7"
export ALERT_COLOR="#14a995"
export DISABLED_COLOR="#707880"

WALLPAPER="The-Matrix-20th.jpg"

GTK_THEME="Adwaita-dark"
