#!/bin/bash

THEME="rails-and-cables"

export BACKGROUND_COLOR="#ededed"
export BACKGROUND_ALT_COLOR="#E5E5E5"
export FOREGROUND_COLOR="#676767"
export PRIMARY_COLOR="#000000"
export SECONDARY_COLOR="#8ABEB7"
export ALERT_COLOR="#A54242"
export DISABLED_COLOR="#707880"

WALLPAPER="rails-and-cables.jpg"

GTK_THEME="Adwaita-light"
