require("core.plugin-config.vimtex")
require("core.plugin-config.luasnip")
require("core.plugin-config.lualine")
require("core.plugin-config.nvim-tree")
require("core.plugin-config.treesitter")
require("core.plugin-config.telescope")
-- require("core.plugin-config.lsp-config")
require("core.plugin-config.newpaper")
require("core.plugin-config.hardtime")
require("core.plugin-config.cmp")
-- require("core.plugin-config.null-ls")
