#!/bin/bash 

# Simple script to change brightness level by editing the corresponding file.
# Expects one parameter for the percentage increment.

intel_backlight=/sys/class/backlight/intel_backlight
max_brightness=$(< $intel_backlight/max_brightness)
inc=$(($1*$max_brightness/100))

current=$(< $intel_backlight/brightness)
new=$(($current + $inc))

if [ $new -gt $max_brightness ]; then
	new=$max_brightness
elif [ $new -lt 0 ]; then
	new=0
fi

echo $new > $intel_backlight/brightness
