#!/bin/sh

# Basic snapshot-style rsync backup script 

# Name of the disk used for the backups
DISK="MyDisk"

# Config
OPT="-aPh"
LINK="--link-dest=/run/media/${USER}/${DISK}/snapshots/last/" 
EXCL="--exclude /santi/.bitmonero/** 
--exclude /santi/.cache/ 
--exclude /santi/.local/ 
--exclude /santi/videos/Movies/ 
--exclude /santi/videos/TV_Shows/ 
--exclude /santi/videos/.*
--exclude /santi/pictures/.*
--exclude /santi/downloads/ISOs/
--exclude /santi/downloads/Apps/"
SRC="/home/"
SNAP="/run/media/${USER}/${DISK}/snapshots/"
LAST="${SNAP}/last"
date=`date "+%Y-%b-%d:_%T"`

# Run rsync to create snapshot
rsync $OPT $EXCL $LINK $SRC ${SNAP}$date

# Remove symlink to previous snapshot
rm -f $LAST

# Create new symlink to latest snapshot for the next backup to hardlink
ln -s ${SNAP}$date $LAST
