#!/bin/bash

THEME="dark-leaves"

export BACKGROUND_COLOR="#172c25"
export BACKGROUND_ALT_COLOR="#455a4b"
export FOREGROUND_COLOR="#dae2e5"
export PRIMARY_COLOR="#977f5e"
export SECONDARY_COLOR="#8ABEB7"
export ALERT_COLOR="#14a995"
export DISABLED_COLOR="#707880"

WALLPAPER="pexels-cátia-matos-1072179.jpg"

GTK_THEME="Adwaita-dark"
